### PR TITLE
Create rakib.html

### PR DESCRIPTION
**Pull request by omiq17**
I have created my file rakib.html. It will be nice if you add this to your repository.

### CODE REVIEW

**Comment by mahbubevan** [comment]
Hello Mr. Raqib , feel nice to working with u

**Comment by omiq17** [comment]
I can see you...

**Comment by omiq17** [comment]
Please merge the pull request....

**Comment by mahbubevan** [comment]
I have seen your code. Do you really think it should merged ??? :dancer:

**Comment by omiq17** [comment]
just merge for checking then delete if you want....

**Comment by mahbubevan** [comment]
is it okay now ??

**Comment by mahbubevan** [comment]
i was joking mammamiah

**Comment by omiq17** [comment]
well done!

**Comment by mahbubevan** [comment]
start your work as you want i am going for 20 minute for Esha Prayer.

**Pull request merged**
